version: '3'

services:

  laravel-app:
    build: ./.docker/nginx
    container_name: nginx_futeba
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      args:
        user: b4ra0
        uid: 1000
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: php_futeba
    restart: unless-stopped
    ports:
      - "8001:81"
    volumes:
      - ./:/var/www

  postgres:
    build: ./.docker/postgres
    container_name: postgres_futeba
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: futeba_bd
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - /home/pc/volumes_idrip/postgres:/var/lib/postgresql/data
