name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.image_name }}:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/${{ vars.image_name }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ vars.image_name }}:$(date +'%Y%m%d%H%M%S')
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.image_name }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.image_name }}:$(date +'%Y%m%d%H%M%S')
